---
- name: Configure application
  hosts: all
  become: true
  become_method: sudo
  vars:
      repository_url: https://github.com/sigidpam/vagrant-ansible-flask.git
      repository_path: /home/vagrant/

- name: Add key for deadsnakes PPA
  apt_key:
     keyserver: keyserver.ubuntu.com
     id: F23C5A6CF475977595C89F51BA6932366A755776
     state: present

- name: Add deadsnakes PPA
  apt_repository:
     repo: deb http://ppa.launchpad.net/deadsnakes/nightly/ubuntu bionic main
     state: present  
  
  tasks:
    - name: Install packages
      apt: update_cache=yes name={{ item }} state=present
      with_items:
          - git
          - python3.8
          - python3-pip
          - nginx
    
    - name: Install with pip3
      pip:
         with_items:
           - virtualenv
           - flask
           - Werkzeug
         executable: pip3        

    - name: Clone repository
      git: repo='{{ repository_url }}' dest='{{ repository_path }}'

    - name: Install requirements
      pip: requirements='{{ repository_path }}/requirements.txt'
      
